version: 1.0.{build}

# Operating system (build VM template)
os: Visual Studio 2015 CTP

environment:
  matrix:
    - VS_VERSION: MSVC2015

build_script:
  - git submodule update --init --recursive
  - gem install bundler
  - vcbuild.bat %VS_VERSION%

test_script:
  - vcbuild.bat %VS_VERSION% test
  - vcbuild.bat %VS_VERSION% inttest
