# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop
    - /feature\/.*/

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      TOOLSET: msvc-9.0,msvc-10.0,msvc-11.0,msvc-12.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLSET: msvc-14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1
      CXXSTD: 14,17

install:
  - set BOOST_BRANCH=develop
  - if "%APPVEYOR_REPO_BRANCH%" == "master" set BOOST_BRANCH=master
  - cd ..
  - git clone -b %BOOST_BRANCH% https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule init libs/align
  - git submodule init libs/assert
  - git submodule init libs/atomic
  - git submodule init libs/config
  - git submodule init libs/core
  - git submodule init libs/detail
  - git submodule init libs/functional
  - git submodule init libs/integer
  - git submodule init libs/move
  - git submodule init libs/predef
  - git submodule init libs/preprocessor
  - git submodule init libs/static_assert
  - git submodule init libs/throw_exception
  - git submodule init libs/type_traits
  - git submodule init tools/build
  - git submodule update
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\smart_ptr
  - cmd /c bootstrap
  - b2 headers

build: off

test_script:
  - if not "%CXXSTD%" == "" set CXXSTD=cxxstd=%CXXSTD%
  - b2 -j 3 libs/smart_ptr/test toolset=%TOOLSET% %CXXSTD%
