# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++03

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.7 CXXSTD=c++03
      addons:
        apt:
          packages:
            - g++-4.7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.7 CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-4.7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.8 CXXSTD=c++03
      addons:
        apt:
          packages:
            - g++-4.8
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.8 CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-4.8
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.9 CXXSTD=c++03
      addons:
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.9 CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++03
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=c++14
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++03
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++11
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++14
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=c++1z
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=gnu++03
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=gnu++11
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=gnu++14
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=gnu++1z
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03

    - os: linux
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.5 CXXSTD=c++03
      addons:
        apt:
          packages:
            - clang-3.5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.5 CXXSTD=c++11
      addons:
        apt:
          packages:
            - clang-3.5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.6 CXXSTD=c++03
      addons:
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.6 CXXSTD=c++11
      addons:
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.7 CXXSTD=c++03
      addons:
        apt:
          packages:
            - clang-3.7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.7 CXXSTD=c++11
      addons:
        apt:
          packages:
            - clang-3.7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=c++03
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=c++11
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=c++14
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=c++1z
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=c++03
      addons:
        apt:
          packages:
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=c++11
      addons:
        apt:
          packages:
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=c++14
      addons:
        apt:
          packages:
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=c++1z
      addons:
        apt:
          packages:
            - clang-3.9
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03
      osx_image: xcode8.2

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11
      osx_image: xcode8.2

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14
      osx_image: xcode8.2

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z
      osx_image: xcode8.1

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03
      osx_image: xcode8.1

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11
      osx_image: xcode8.1

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14
      osx_image: xcode8.1

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z
      osx_image: xcode8.1

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03
      osx_image: xcode8.0

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11
      osx_image: xcode8.0

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14
      osx_image: xcode8.0

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z
      osx_image: xcode8.0

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03
      osx_image: xcode7.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11
      osx_image: xcode7.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14
      osx_image: xcode7.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z
      osx_image: xcode7.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++03
      osx_image: xcode6.4

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++11
      osx_image: xcode6.4

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++14
      osx_image: xcode6.4

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=c++1z
      osx_image: xcode6.4

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init libs/assert
  - git submodule update --init libs/bind
  - git submodule update --init libs/core
  - git submodule update --init libs/detail
  - git submodule update --init libs/function
  - git submodule update --init libs/integer
  - git submodule update --init libs/move
  - git submodule update --init libs/mpl
  - git submodule update --init libs/preprocessor
  - git submodule update --init libs/static_assert
  - git submodule update --init libs/throw_exception
  - git submodule update --init libs/type_index
  - git submodule update --init libs/utility
  - cp -r $TRAVIS_BUILD_DIR/* libs/type_traits
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - (cd libs/config/test && ../../../b2 config_info_travis_install toolset=$TOOLSET && ./config_info_travis)
  - ./b2 -j3 libs/type_traits/test toolset=$TOOLSET

notifications:
  email:
    on_success: always
